### ISSUE TITLE
chrome extension seems to ignore select fields

### ISSUE THREAD

**Issue by danielzzz** [tebelorg/TA.Gui#11]
Hi, this is what I do:

1. go to the URL 
2. click at a select field and select an option

RESULT:
only step 1 is recorded.

thanks, dan

**Comment by kensoh** [comment]
Hi Dan / @danielzzz, thank you for reporting this issue. This hasn't been implemented in current iteration of chrome extension.

I expect between beta and initial release, the chrome extension is going to have a lot of new functionalities and be a lot better!

I'm keeping the issue open and I appreciate feedback like these, please keep it coming :)

Kind Regards,
Ken

**Comment by danielzzz** [comment]
Is it possible to set up a select value from the script directly? 
I've been trying using something like:
```
enter //*[@id="OrderCompanyId"] as 111 
```
but it doesn't seem to work..

**Comment by kensoh** [comment]
Hi @danielzzz, I'm afraid this is currently not natively supported yet by CasperJS (the underlying driver), https://github.com/casperjs/casperjs/issues/1390

However, as part of looking at this for the Chrome extension support, I'll also be looking at workarounds like the one suggested in above thread and simplify it probably with a new step call select

**Comment by kensoh** [comment]
Hi @danielzzz and future readers, i've just commited a new step called select / choose. it uses a custom function to interact with dropdown options as casperjs does not support dropdown option natively at the moment (casperjs issue 1390). Have tested with the following automation flow

```
http://www.seleniumeasy.com/test/basic-select-dropdown-demo.html
select select-demo as Tuesday
wait 2.5
select select-demo as Friday
wait 2.5
```

note to self - update readme of this new step, update test signature, check chrome extension for possible implementation

**Comment by kensoh** [comment]
Hi @danielzzz and future readers, i've just commited a new step called select / choose. it uses a custom function to interact with dropdown options as casperjs does not support dropdown option natively at the moment (casperjs issue 1390). Have tested with the following automation flow

```
http://www.seleniumeasy.com/test/basic-select-dropdown-demo.html
select select-demo as Tuesday
wait 2.5
select select-demo as Friday
wait 2.5
```

note to self - update readme of this new step, test signature, sample flows tutorial, check chrome extension for possible implementation

**Comment by kensoh** [comment]
@danielzzz besides adding select step, i've added option selection recording into chrome. this is a custom workaround not yet officially supported natively in casperjs so it may break. let me know if it works for your use case so that this can be fine-tuned further as it goes, with new datapoints.

below is an actual recording using the chrome extension and works on playback when ran with firefox option - 

```
http://www.seleniumeasy.com/test/basic-select-dropdown-demo.html
click select-demo
select select-demo as Tuesday
wait
select select-demo as Friday
wait
```
