### ISSUE TITLE
problems using firefox on linux

### ISSUE THREAD

**Issue by danielzzz** [tebelorg/TA.Gui#13]
I created a new issue from #12 as this is not related to that.

I have problems using ta.gui with firefox on ubuntu 16.04.2 LTS

```
./tagui my_test.gui firefox
Gecko error: it seems /usr/bin/firefox is not compatible with SlimerJS.
See Gecko version compatibility. If version is correct, launch slimerjs
with --debug=true to see Firefox error message
```

Firefox version: 51.0.1 (64-bit

**Comment by kensoh** [comment]
Thanks for raising this! I'll set as feedback, this is an underlying error message between SlimerJS and Firefox. Can you take a look at application.ini in your SlimerJS installation for your maxVersion and minVersion? I had this problem as well and added this check to the readme.

https://docs.slimerjs.org/current/installation.html#using-unstable-version-or-very-old-versions-of-firefox

**Comment by danielzzz** [comment]
great, this helped!

I changed the maxVersion to something higher than the one I'm using and now it's working.
thanks!

**Comment by kensoh** [comment]
Thanks @danielzzz for your feedback, I will adjust readme to make this clearer. The issue happened is that SlimerJS (for security reasons) setting caps the upper limit in order to prevent use of unstable version and also caps the lower limit to prevent use of very old versions.
