### ISSUE TITLE
Silence option missing

### ISSUE THREAD

**Issue by gruselglatz** [tebelorg/TA.Gui#14]
It would be awsome if there is an silence option, so TA.Gui only prints out something on print and echo commands.

**Comment by kensoh** [comment]
Thanks @gruselglatz for your feedback :) I think that this is an option that I also want to use myself, for example piping the output to some other downstream apps etc for consumption, or to just reduce screen clutter once the flow is tested working. I'll keep this issue open as enhancement.

**Comment by kensoh** [comment]
@gruselglatz the enhancement has been implemented! Added quiet option into code and readme, do have a look and let me know if it's all good :)

quiet - run without output except for explicit output echo / show / check / api / errors etc

**Comment by kensoh** [comment]
@gruselglatz the enhancement has been implemented! Added quiet option into code and readme, do have a look and let me know if something is cranky :)

quiet - run without output except for explicit output echo / show / check / api / errors etc
